version: "3.5"
services:
  build-page:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    working_dir: /home
    command: bash -c "pip install jupyter-book && jupyter-book build /src"
